---

kind: pipeline
name: default
type: docker

platform:
  arch: amd64
  os: linux

steps:
  - name: publish_docker
    image: docker.pkg.github.com/vegaprotocol/devops-infra/cipipeline-docker:18.09.9
    volumes:
      - name: dockersock
        path: /run/docker.sock
    environment:
      DOCKER_HOST: unix:///run/docker.sock
      DOCKER_CONFIG_JSON:
        from_secret: dockerconfig
    commands:
      - mkdir -p "$$HOME/.docker" ; echo "$$DOCKER_CONFIG_JSON" >"$$HOME/.docker/config.json" ; unset DOCKER_CONFIG_JSON
      - tag="$${DRONE_TAG:-$${DRONE_BRANCH:-}}"
      - test -n "$$tag" || exit 1
      - image="docker.pkg.github.com/vegaprotocol/multisigcontrol/multisigcontrol:$$tag"
      - docker build -t "$$image" .
      - docker push "$$image"
    depends_on: []
    when:
      ref:
        - refs/heads/master
        - refs/heads/develop
        - refs/tags/*

volumes:
  - name: dockersock
    host:
      path: /run/docker.sock

image_pull_secrets:
  - dockerconfig
